// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrVhvFeNTOr2M3wt29uUuRtCnEwWYNI8',
    appId: '1:838665250210:web:65a8b456f0ae428fb3fefb',
    messagingSenderId: '838665250210',
    projectId: 'note-app-with-flutter',
    authDomain: 'note-app-with-flutter.firebaseapp.com',
    storageBucket: 'note-app-with-flutter.appspot.com',
    measurementId: 'G-BLB83K8B8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzHNsRWtEMTZLUEnEQpIduO1GXhwLwSGU',
    appId: '1:838665250210:android:5751fb7b72f46f28b3fefb',
    messagingSenderId: '838665250210',
    projectId: 'note-app-with-flutter',
    storageBucket: 'note-app-with-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAqJ1O_qo6ldR9YBH98mtT3on86lYzTjc',
    appId: '1:838665250210:ios:64bbaa129d9a502eb3fefb',
    messagingSenderId: '838665250210',
    projectId: 'note-app-with-flutter',
    storageBucket: 'note-app-with-flutter.appspot.com',
    iosClientId: '838665250210-24ue9oauifojh51fmbccniovvrl9b6tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAqJ1O_qo6ldR9YBH98mtT3on86lYzTjc',
    appId: '1:838665250210:ios:64bbaa129d9a502eb3fefb',
    messagingSenderId: '838665250210',
    projectId: 'note-app-with-flutter',
    storageBucket: 'note-app-with-flutter.appspot.com',
    iosClientId: '838665250210-24ue9oauifojh51fmbccniovvrl9b6tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningDart',
  );
}
